apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: helm-mysql
  namespace: helm-mysql
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: 
          - helm-mysql
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
  labels:
    app: helm-mysql
  name: helm-mysql-subscription-1
  namespace: helm-mysql
spec:
  channel: hchartshelmsh-stable-ns/hchartshelmsh-stable
  name: mysql
  packageOverrides:
  - packageName: mysql
    packageAlias: mysql
  packageFilter:
    version: "1.6.9"
  placement:
    placementRef:
      kind: PlacementRule
      name: helm-mysql-placement-1
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: helm-mysql
  name: helm-mysql-placement-1
  namespace: helm-mysql
spec:
  clusterSelector:
    matchLabels:
      'local-cluster': 'true'
