apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-mysql
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: helm-mysql-placement
        requeueAfterSeconds: 180
  template:
    metadata:
      name: helm-mysql-{{name}}
      labels:
        velero.io/exclude-from-backup: "true"
    spec:
      project: default
      source:
        repoURL: https://github.com/kcalliga/helm-mysql
        targetRevision: main
        path: mysql
      destination:
        namespace: helm-mysql
        server: "{{server}}"
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: helm-mysql-placement
  namespace: openshift-gitops
spec:
  clusterSets:
    - openshift
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: local-cluster
              operator: In
              values:
                - "true"
